name: fastcut
description: FastCut beta — mobile quick video editor
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # видео
  video_player: ^2.6.0

  # выбор файла/видео
  file_picker: ^5.2.2

  # разрешения
  permission_handler: ^10.4.0

  # ffmpeg для экспорта
  ffmpeg_kit_flutter_full_gpl: ^4.5.1

  # путь для сохранения
  path_provider: ^2.0.11

  # id для клипов
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
